# dashboard/app.py

import streamlit as st
import pandas as pd
import time
import os

# -------------------------------
# Page Configuration
# -------------------------------
st.set_page_config(
    page_title="Real-Time Social Media Analytics",
    layout="wide"
)

st.title("📊 Real-Time Social Media Analytics Dashboard")

# -------------------------------
# File Path (CSV generated by streamer)
# -------------------------------
DATA_FILE = "data/streamed_data.csv"

# -------------------------------
# Create placeholders
# -------------------------------
metric_placeholder = st.empty()
table_placeholder = st.empty()

# -------------------------------
# Function to load data safely
# -------------------------------
def load_data():
    if os.path.exists(DATA_FILE):
        try:
            df = pd.read_csv(DATA_FILE)
            return df
        except:
            return pd.DataFrame()
    return pd.DataFrame()

# -------------------------------
# Real-time updating loop
# -------------------------------
while True:

    streamed_data = load_data()

    if not streamed_data.empty:

        # ✅ FIXED (single element inside placeholder)
        metric_placeholder.metric(
            label="Tweets Processed",
            value=len(streamed_data)
        )

        # Show latest data
        table_placeholder.dataframe(
            streamed_data.tail(10),
            use_container_width=True
        )

    else:
        metric_placeholder.write("Waiting for data stream...")

    # Refresh every 3 seconds
    time.sleep(3)